#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Nov 10, 2024 09:12:31 PM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import agregarlibro_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: agregarlibro_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+468+138")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#98e4fe")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.167, rely=0.111, relheight=0.744
                , relwidth=0.675)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#9b0a64")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Label2_1 = tk.Label(self.Frame1)
        self.Label2_1.place(relx=0.198, rely=0.418, height=21, width=34)
        self.Label2_1.configure(activebackground="#d9d9d9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#9b0a64")
        self.Label2_1.configure(compound='left')
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Segoe UI} -size 9")
        self.Label2_1.configure(foreground="#ffffff")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="#000000")
        self.Label2_1.configure(text='''Autor:''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.198, rely=0.269, height=21, width=34)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#9b0a64")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Título:''')

        self.Label2_1_1 = tk.Label(self.Frame1)
        self.Label2_1_1.place(relx=0.198, rely=0.567, height=21, width=54)
        self.Label2_1_1.configure(activebackground="#d9d9d9")
        self.Label2_1_1.configure(activeforeground="black")
        self.Label2_1_1.configure(anchor='w')
        self.Label2_1_1.configure(background="#9b0a64")
        self.Label2_1_1.configure(compound='left')
        self.Label2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label2_1_1.configure(foreground="#ffffff")
        self.Label2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1.configure(highlightcolor="#000000")
        self.Label2_1_1.configure(text='''Género:''')

        self.btnRegresar = tk.Button(self.Frame1)
        self.btnRegresar.place(relx=0.099, rely=0.866, height=26, width=57)
        self.btnRegresar.configure(activebackground="#d9d9d9")
        self.btnRegresar.configure(activeforeground="black")
        self.btnRegresar.configure(background="#fecb01")
        self.btnRegresar.configure(command=agregarlibro_support.doRegresar)
        self.btnRegresar.configure(disabledforeground="#a3a3a3")
        self.btnRegresar.configure(foreground="#000000")
        self.btnRegresar.configure(highlightbackground="#d9d9d9")
        self.btnRegresar.configure(highlightcolor="#000000")
        self.btnRegresar.configure(text='''Regresar''')

        self.btnRegresar_1 = tk.Button(self.Frame1)
        self.btnRegresar_1.place(relx=0.741, rely=0.866, height=26, width=57)
        self.btnRegresar_1.configure(activebackground="#d9d9d9")
        self.btnRegresar_1.configure(activeforeground="black")
        self.btnRegresar_1.configure(background="#fecb01")
        self.btnRegresar_1.configure(command=agregarlibro_support.doAceptar)
        self.btnRegresar_1.configure(disabledforeground="#a3a3a3")
        self.btnRegresar_1.configure(font="-family {Segoe UI} -size 9")
        self.btnRegresar_1.configure(foreground="#000000")
        self.btnRegresar_1.configure(highlightbackground="#d9d9d9")
        self.btnRegresar_1.configure(highlightcolor="#000000")
        self.btnRegresar_1.configure(text='''Aceptar''')

        _style_code()
        self.TEntry1 = ttk.Entry(self.Frame1)
        self.TEntry1.place(relx=0.37, rely=0.269, relheight=0.057
                , relwidth=0.306)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.TEntry2 = ttk.Entry(self.Frame1)
        self.TEntry2.place(relx=0.37, rely=0.418, relheight=0.057
                , relwidth=0.306)
        self.TEntry2.configure(takefocus="")
        self.TEntry2.configure(cursor="ibeam")

        self.TEntry3 = ttk.Entry(self.Frame1)
        self.TEntry3.place(relx=0.37, rely=0.567, relheight=0.057
                , relwidth=0.306)
        self.TEntry3.configure(takefocus="")
        self.TEntry3.configure(cursor="ibeam")

        self.Label2_1_1_1 = tk.Label(self.Frame1)
        self.Label2_1_1_1.place(relx=0.198, rely=0.716, height=21, width=104)
        self.Label2_1_1_1.configure(activebackground="#d9d9d9")
        self.Label2_1_1_1.configure(activeforeground="black")
        self.Label2_1_1_1.configure(anchor='w')
        self.Label2_1_1_1.configure(background="#9b0a64")
        self.Label2_1_1_1.configure(compound='left')
        self.Label2_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label2_1_1_1.configure(foreground="#ffffff")
        self.Label2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1_1.configure(highlightcolor="#000000")
        self.Label2_1_1_1.configure(text='''Año:''')

        self.TEntry4 = ttk.Entry(self.Frame1)
        self.TEntry4.place(relx=0.37, rely=0.716, relheight=0.057
                , relwidth=0.306)
        self.TEntry4.configure(takefocus="")
        self.TEntry4.configure(cursor="fleur")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.321, rely=0.119, height=21, width=146)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='e')
        self.Label1.configure(background="#9b0a64")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Completa la información''')

    def popup1(self, event, *args, **kwargs):
        self.Popupmenu1 = tk.Menu(self.top, tearoff=0)
        self.Popupmenu1.configure(background=_bgcolor)
        self.Popupmenu1.configure(foreground=_fgcolor)
        self.Popupmenu1.configure(font="TkMenuFont")
        self.Popupmenu1.post(event.x_root, event.y_root)

def start_up():
    agregarlibro_support.main()

if __name__ == '__main__':
    agregarlibro_support.main()




