#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Nov 11, 2024 01:35:39 AM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import consultas_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: consultas_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+597+181")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#98e4fe")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.combobox = tk.StringVar()

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.05, rely=0.067, relheight=0.856, relwidth=0.908)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#9b0a64")
        self.Frame1.configure(cursor="fleur")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.44, rely=0.104, height=21, width=64)
        self.Label1.configure(activebackground="#9b0a64")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#9b0a64")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Consultas''')

        _style_code()
        self.TEntry1 = ttk.Entry(self.Frame1)
        self.TEntry1.place(relx=0.147, rely=0.26, relheight=0.049
                , relwidth=0.246)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="fleur")

        self.TEntry1_1 = ttk.Entry(self.Frame1)
        self.TEntry1_1.place(relx=0.147, rely=0.416, relheight=0.049
                , relwidth=0.246)
        self.TEntry1_1.configure(font="-family {Segoe UI} -size 9")
        self.TEntry1_1.configure(cursor="fleur")

        self.TCombobox1 = ttk.Combobox(self.Frame1)
        self.TCombobox1.place(relx=0.147, rely=0.571, relheight=0.049
                , relwidth=0.251)
        self.TCombobox1.configure(textvariable=self.combobox)
        self.TCombobox1.configure(takefocus="")

        self.Label1_1_1 = tk.Label(self.Frame1)
        self.Label1_1_1.place(relx=0.037, rely=0.416, height=21, width=64)
        self.Label1_1_1.configure(activebackground="#9b0a64")
        self.Label1_1_1.configure(activeforeground="black")
        self.Label1_1_1.configure(anchor='w')
        self.Label1_1_1.configure(background="#9b0a64")
        self.Label1_1_1.configure(compound='left')
        self.Label1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label1_1_1.configure(foreground="#ffffff")
        self.Label1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1.configure(highlightcolor="#000000")
        self.Label1_1_1.configure(text='''Autor''')

        self.Label1_1 = tk.Label(self.Frame1)
        self.Label1_1.place(relx=0.037, rely=0.26, height=21, width=64)
        self.Label1_1.configure(activebackground="#9b0a64")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(background="#9b0a64")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label1_1.configure(foreground="#ffffff")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="#000000")
        self.Label1_1.configure(text='''Nombre''')

        self.Label1_1_1_1 = tk.Label(self.Frame1)
        self.Label1_1_1_1.place(relx=0.037, rely=0.571, height=21, width=64)
        self.Label1_1_1_1.configure(activebackground="#9b0a64")
        self.Label1_1_1_1.configure(activeforeground="black")
        self.Label1_1_1_1.configure(anchor='w')
        self.Label1_1_1_1.configure(background="#9b0a64")
        self.Label1_1_1_1.configure(compound='left')
        self.Label1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label1_1_1_1.configure(foreground="#ffffff")
        self.Label1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1_1.configure(highlightcolor="#000000")
        self.Label1_1_1_1.configure(text='''Género''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.128, rely=0.883, height=26, width=57)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#fdab02")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Regresar''')

        self.TEntry1_1_1 = ttk.Entry(self.Frame1)
        self.TEntry1_1_1.place(relx=0.147, rely=0.727, relheight=0.049
                , relwidth=0.246)
        self.TEntry1_1_1.configure(font="-family {Segoe UI} -size 9")
        self.TEntry1_1_1.configure(cursor="fleur")

        self.Label1_1_1_1_1 = tk.Label(self.Frame1)
        self.Label1_1_1_1_1.place(relx=0.037, rely=0.727, height=21, width=64)
        self.Label1_1_1_1_1.configure(activebackground="#9b0a64")
        self.Label1_1_1_1_1.configure(activeforeground="black")
        self.Label1_1_1_1_1.configure(anchor='w')
        self.Label1_1_1_1_1.configure(background="#9b0a64")
        self.Label1_1_1_1_1.configure(compound='left')
        self.Label1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1_1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label1_1_1_1_1.configure(foreground="#ffffff")
        self.Label1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1_1_1.configure(highlightcolor="#000000")
        self.Label1_1_1_1_1.configure(text='''Año''')

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.532, rely=0.234, relheight=0.551
                , relwidth=0.393)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="#000000")
        self.Listbox1.configure(selectbackground="#d9d9d9")
        self.Listbox1.configure(selectforeground="black")

def start_up():
    consultas_support.main()

if __name__ == '__main__':
    consultas_support.main()




