#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Nov 09, 2024 05:03:06 PM EST  platform: Windows NT
#    Nov 09, 2024 06:01:07 PM EST  platform: Windows NT

import sys
import tkinter as tk
from tkinter.constants import *
import navegacion_support 

def doIngresar():
    global root
    root.destroy()  # Destruye la ventana actual antes de abrir la nueva
    navegacion_support.main()  # Inicia la ventana de navegación

def main():
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    global _top1, _w1
    _top1 = root
    from interfaz import Toplevel1 
    _w1 = Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    main()


