#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Nov 10, 2024 12:11:23 PM EST  platform: Windows NT
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import consultas_support
import navegacion
import agregarlibro_support
import visualizacion_support

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = navegacion.Toplevel1(_top1)
    root.mainloop()

def doAnadir():
    global root
    root.destroy()  # Destruye la ventana actual antes de abrir la nueva
    agregarlibro_support.main()  # Inicia la ventana de navegación

def doConsultar(*args):
    global root
    root.destroy()  # Destruye la ventana actual antes de abrir la nueva
    consultas_support.main()  # Inicia la ventana de navegación

def doOrdenar(*args):
    global root
    root.destroy()  # Destruye la ventana actual antes de abrir la nueva
    consultas_support.main()  # Inicia la ventana de navegación

def doVisualizar(*args):
    global root
    root.destroy()  # Destruye la ventana actual antes de abrir la nueva
    visualizacion_support.main()  # Inicia la ventana de navegación

if __name__ == '__main__':
    navegacion.start_up()

