#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Nov 10, 2024 12:11:23 PM EST  platform: Windows NT

import sys
import tkinter as tk
from tkinter.constants import *
import navegacion  # Asume que Navegacion es el módulo que contiene la definición de Toplevel1 para navegación

def main():
    '''Main entry point for the Navegacion application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    global _top1, _w1
    _top1 = root
    _w1 = navegacion.Toplevel1(_top1)  # Asegúrate de que Navegacion contiene una clase llamada Toplevel1
    root.mainloop()

if __name__ == '__main__':
    main()


